from enum import Enum


class AffineTransformations(Enum):
    NONE = 0
    ROTATE_90 = 1
    ROTATE_180 = 2
    ROTATE_270 = 3

    REFLECT_HORIZONTALLY = 4
    ROTATE_90_AND_REFLECT_HORIZONTALLY = 5
    ROTATE_180_AND_REFLECT_HORIZONTALLY = 6
    ROTATE_270_AND_REFLECT_HORIZONTALLY = 7

    REFLECT_VERTICALLY = 8
    ROTATE_90_AND_REFLECT_VERTICALLY = 9
    ROTATE_180_AND_REFLECT_VERTICALLY = 10
    ROTATE_270_AND_REFLECT_VERTICALLY = 11

    REFLECT_HORIZONTALLY_AND_VERTICALLY = 12
    ROTATE_90_AND_REFLECT_HORIZONTALLY_AND_VERTICALLY = 13
    ROTATE_180_AND_REFLECT_HORIZONTALLY_AND_VERTICALLY = 14
    ROTATE_270_AND_REFLECT_HORIZONTALLY_AND_VERTICALLY = 15
